### ISSUE TITLE
Is RISurConv a plug-and-play module?

### ISSUE THREAD

**Issue by whuhxb** [cszyzhang/RISurConv#1]
Dear Authors:

        Thanks for your great work!

        The rotation-invariance is a common property in point cloud data. As the RISurConv module is effective, is the RISurConv a play-and-plug module for other baselines? Have you ever tested the RISurConv module with other point cloud classification baselines? Thanks a lot!

Best wishes.

**Comment by cszyzhang** [comment]
> Dear Authors:
> 
> ```
>     Thanks for your great work!
> 
>     The rotation-invariance is a common property in point cloud data. As the RISurConv module is effective, is the RISurConv a play-and-plug module for other baselines? Have you ever tested the RISurConv module with other point cloud classification baselines? Thanks a lot!
> ```
> 
> Best wishes.

Hi hxb,
Yes, it is a plug-and-play module. Please check the supplementary section D.

**Comment by whuhxb** [comment]
> > Dear Authors:
> > ```
> >     Thanks for your great work!
> > 
> >     The rotation-invariance is a common property in point cloud data. As the RISurConv module is effective, is the RISurConv a play-and-plug module for other baselines? Have you ever tested the RISurConv module with other point cloud classification baselines? Thanks a lot!
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Best wishes.
> 
> Hi hxb, Yes, it is a plug-and-play module. Please check the supplementary section D.

Thanks for your kind reply!
