### ISSUE TITLE
ShapeNet installation: broken link 

### ISSUE THREAD

**Issue by samhy99** [cszyzhang/RISurConv#3]
Hi, 

I'm currently trying to setup and replicate your work. One thing I've noticed is that the link provided for the ShapeNet data seems to be defective. I'm not sure if this is a temporary issue or is the link broken, but I was able to get the dataset from Zenodo instead at [this link ](https://zenodo.org/records/10089706/files/archive.zip?download=1). 

Cheers,

**Comment by cszyzhang** [comment]
Thank you for pointing out this.

**Comment by cszyzhang** [comment]
Thank you for pointing out this. Yes, the new link you suggested is good.
